on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build and deploy
        run: ./mvnw clean deploy
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}